name: Testing
on:
  - push
  - pull_request

jobs:
  macos-testing:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install RGBDS
        run: |
          brew install rgbds
      - name: Test hardware.inc
        run: |
          rgbasm hardware.inc
      - name: Test hardware_compat.inc
        run: |
          rgbasm -P hardware.inc hardware_compat.inc
      - name: Test sgb.inc
        run: |
          rgbasm sgb.inc

  windows-testing:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install RGBDS
        run: |
          # Find the URL of the latest Win64 release with the GitHub API
          $githubLatestReleasesAPI = "https://api.github.com/repos/gbdev/rgbds/releases/latest"
          $githubReleaseURLs = ((Invoke-WebRequest $githubLatestReleasesAPI) | ConvertFrom-Json).assets.browser_download_url
          $githubWinReleaseURL = ($githubReleaseURLs | Select-String "win64").ToString()
          # Download latest release
          Invoke-WebRequest $githubWinReleaseURL -OutFile rgbds.zip
          Expand-Archive rgbds.zip
          # Move files out of subdirectories if present
          Get-ChildItem -Path rgbds -Recurse -File | Move-Item -Destination rgbds -Force
      - name: Test hardware.inc
        run: |
          rgbds/rgbasm.exe hardware.inc
      - name: Test hardware_compat.inc
        run: |
          rgbds/rgbasm.exe -P hardware.inc hardware_compat.inc
